// [Fog-Graphics Library - Public API]
//
// [License]
// MIT, See COPYING file in package

// [Precompiled Headers]
#if defined(FOG_PRECOMP)
#include FOG_PRECOMP
#endif // FOG_PRECOMP

// [Dependencies]
#include <Fog/Graphics/Constants_p.h>

namespace Fog {

uint32_t OperatorCharacteristics[OPERATOR_COUNT] =
{
  OPERATOR_CHAR_SRC,
  OPERATOR_CHAR_DST,
  OPERATOR_CHAR_SRC_OVER,
  OPERATOR_CHAR_DST_OVER,
  OPERATOR_CHAR_SRC_IN,
  OPERATOR_CHAR_DST_IN,
  OPERATOR_CHAR_SRC_OUT,
  OPERATOR_CHAR_DST_OUT,
  OPERATOR_CHAR_SRC_ATOP,
  OPERATOR_CHAR_DST_ATOP,
  OPERATOR_CHAR_XOR,
  OPERATOR_CHAR_CLEAR,
  OPERATOR_CHAR_ADD,
  OPERATOR_CHAR_SUBTRACT,
  OPERATOR_CHAR_MULTIPLY,
  OPERATOR_CHAR_SCREEN,
  OPERATOR_CHAR_DARKEN,
  OPERATOR_CHAR_LIGHTEN,
  OPERATOR_CHAR_DIFFERENCE,
  OPERATOR_CHAR_EXCLUSION,
  OPERATOR_CHAR_INVERT,
  OPERATOR_CHAR_INVERT_RGB
};

} // Fog namespace
