// [Fog-Core]
//
// [License]
// MIT, See COPYING file in package

// ============================================================================
// [Fog::Math - Cleanup]
// ============================================================================

// There is no header guard - this file can be included at any time to cleanup
// a mess generated by some C header files.

#if defined(abs)
#undef abs
#endif // abs

#if defined(bound)
#undef bound
#endif // bound

#if defined(min)
#undef min
#endif // min

#if defined(max)
#undef max
#endif // max
